### ISSUE TITLE
Test-kitchen tests are not being run on Vagrant

### ISSUE THREAD

**Issue by eherot** [xhost-cookbooks/openvpn#49]
The trouble seems to be that the bats tests are in `test/integration/default` but when DigitalOcean tests were moved to their own YAML (in commit bdb0b53), the newly created suite in the old Kitchen YAML was named `server`.

**Comment by flaccid** [comment]
@eherot instead of using 'default' in testing, we can we use 'server' and 'client' so we can support both possible roles of a node? The 'client' will still has work to do so that it can correctly start and connect to the server ala vagrant multi-machine mode.

```
suites:
  - name: server
    run_list:
      - recipe[openvpn::server]
    attributes:
      openvpn:
        config:
          verb: 1
          mute: 10
        push_routes:
          - 192.168.10.0 255.255.255.0
        push_options:
          dhcp-option:
            - 'DOMAIN local'
            - 'DOMAIN-SEARCH local'
```
